#!/bin/sh
#
# Post-commit email hook for git.
#
# dsimmons@squiz.co.uk
# 2011-08-12
#

mailto="$(git config hooks.mailinglist)"
subject="$(git config hooks.emailprefix) $(hostname) commit: $(git rev-parse --short HEAD) - $(git show --pretty='format:' --name-only |tr -d '\n')"
message="$(git log -1 -p)"
echo "$message" |mail -s "$subject" "$mailto"
